spring.application.name=cricket_team_managment

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.datasource.url=jdbc:mysql://localhost:3306/cricket_team_management
spring.datasource.username= root
spring.datasource.password= root123